megablocks/layers/moe.py

The bias should be automatically correctly projected to the mlp so this change should be fine. Pytorch FSDP only shards on the first dimension so this change allows the bias to also be sharded.
cc: @vchiley

Enable FSDP sharding for bias

---

megablocks/layers/arguments.py
megablocks/layers/dmoe.py
megablocks/layers/dmoe_test.py
megablocks/layers/mlp.py
megablocks/layers/moe.py
megablocks/ops/padded_scatter.py
megablocks/ops/padded_scatter_test.py
requirements.txt
setup.py

Adds activation quantization to:
* `MemoryOptimizedMLP` in `megablocks/layers/mlp.py`
* `PaddedScatterOp` in `megablocks/ops/padded_scatter.py`
To support this, we also modify:
* `megablocks/layers/arguments.py` for quantization config
* `megablocks/layers/moe.py` to pass through quantization config
* `megablocks/layers/dmoe.py` to pass through quantization config
* `megablocks/layers/dmoe_test.py` to make sure forward and backward run with quantization. Also, _we now test with `memory_optimized_mlp=True`_.
* `megablocks/ops/padded_scatter_test.py` to make sure forward and backward run with quantization.
* `requirements.txt` and `setup.py` to add the quantization library as a dependency.
[Wandb report](https://wandb.ai/mosaic-ml/davis-actq/reports/Activation-Quantization-Summary--Vmlldzo1M …

Add optional activation quantization

---

megablocks/layers/mlp.py
megablocks/turbo_util.py

It looks like the `turbo_util` wrapping and grouped gemm pasting broke it. This PR fixes it.

Fix activation quantization

---

megablocks/layers/mlp.py
megablocks/ops/padded_scatter.py
megablocks/ops/scatter.py

Unpacks saved context once as is required for CPU offloading implementation. Ideally we unpack into named variables, but it's a little messy given what is saved depends on if we quantize or not. I just did simplest change to get it to work, but feel free to suggest refactor if appropriate

Unpack saved context once

---

megablocks/layers/moe.py

Avoid duplicate `.cpu()` call by using cached CPU counts

Avoid duplicate `.cpu()` call

---

megablocks/layers/common.py

Have megablocks rely on torch default precision when creating new tensors. Many external libraries, e.g. HF, rely on this

Have megablocks rely on torch default precision

---

megablocks/layers/arguments.py
megablocks/layers/dmlp_registry.py
megablocks/layers/dmoe.py
megablocks/layers/dmoe_test.py
megablocks/layers/glu.py
megablocks/layers/glu_test.py
megablocks/layers/mlp.py
megablocks/layers/mlp_registry.py
megablocks/layers/testing.py

This change adds GLU blocks to megablocks (replacing vanilla MLPs), and does some refactoring around the mlp types, including an `MLP_TYPE_REGISTRY`. 
Note, this is unoptimized at the moment:
- no support for the memory optimized mlp version yet
- w1 & v1 are not fused into one op that is split

Add GLU support

---

megablocks/layers/dmoe.py
megablocks/layers/moe.py
megablocks/layers/router.py

MegaBlocks currently assumes a 3D input `[sl, bs, hs]` when in fact MegaBlocks should be able to operate on inputs of any multi-dim shape `[*, hs]`
The changes in this PR enable that.
Useful for padded inputs. If we flatten padded inputs with shape: `[sl, bs, hs]` into input with shape: `[sl * bs - num_pad_tok, hs]`, then pad tokens are not part of all2all routing and lbl isn't computed on padding tokens.

Enable generic dimentionality for input

---

megablocks/layers/dmoe.py

There's an extra size call that is unused but makes assumptions about a tensor's dimensions:
https://github.com/stanford-futuredata/megablocks/commit/6e09bc50fbfde38d75d7b741722cd99149014e0e

Removing an extra size call

---

setup.py

Currently the setup.py code only target the current device, making it difficult to build wheels that target many architectures. We are facing this problem in distributing vLLM docker images. 
This PR adds a block that recognizes the environment variable `TORCH_CUDA_ARCH_LIST` which will be interpreted by torch's cuda extension to build for multiple architecture.

Update setup.py to support multiple device capabilities

---

megablocks/layers/moe.py

Currently the model updates the load balancing loss during every forward pass.
So if we have a pipeline like that does validation every X batches, it's going to lead to an assert error like `Expected 6 token_per_experts but found 54`
This PR fixes it so that it only updates the load balancing loss during forward passes of model.train() and not model.eval()

Skip updating load balancing loss on eval

---

megablocks/layers/router.py

I was seeing:
```
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [8192, 2]], which is output 0 of DivBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```
This change addresses that issue.

Change router weight norm from in-place

---

README.md
megablocks/layers/arguments.py
megablocks/layers/dmlp_registry.py
megablocks/layers/dmoe.py
megablocks/layers/dmoe_test.py
megablocks/layers/glu_test.py
megablocks/layers/moe.py

Add mlp_impl flag so that all mlp implementations will be specified with `grouped` or `sparse`
- dmoe_test.py ✅ 
- moe_test.py ✅ 
- glu_test.py ✅ 
End to end run:
- Ran a short training run with grouped to verify it worked

Add dmlp registry args

---

megablocks/layers/router.py

The router.py function,
```python
def _top_k(self, scores):
if self.args.moe_top_k == 1:
return scores.max(dim=-1) # <-- causes weight shape to become [S]
return torch.topk(scores, self.args.moe_top_k, dim=-1) # <-- shape is normally [S,K]
```
caused expert weight norm to be calculated wrong:
```python
expert_weights, expert_indices = self._top_k(scores)
if self.args.moe_normalize_expert_weights:
expert_weights = expert_weights / torch.norm(
expert_weights, p=self.args.moe_normalize_expert_weights,dim=-1, keepdim=True)
```
After this PR, top-1 models with moe_normalize_expert_weights=1 should always have the final weights become 1 (where previously they would be divided weirdly)

Fix `moe_normalize_expert_weights` when `top_k=1`

---

megablocks/layers/moe.py

Megablocks accumulates lb-loss tensors [here](https://github.com/databricks/megablocks/blob/main/megablocks/layers/moe.py#L428) and expects the user to call `clear_load_balancing_loss()` to release the memory.  In our case we compute the lb-loss outside of Megablocks and had a GPU memory leak before we noticed this behaviour.
We can call `clear_load_balancing_loss()` after every Megablocks `forward()`, but it's even better to just avoid accumulating these tensors if Megablocks' lb-loss calculation is not needed - which can already be signaled by passing 0 to `Arguments.args.moe_loss_weight`

dont save moe lb-loss tensors if args.moe_loss_weight=0

---

.github/workflows/pr-gpu.yaml

Change the runner from `linux-ubuntu-latest`, one of our runners, to the default Github Runner `ubutnu-latest`. This is because to use `linux-ubuntu-latest` we need the repo to be on the IP allow list and we don't have that right now.

Change Runner in GA

---

.github/workflows/pr-gpu.yaml

[LLM-Foundry](https://github.com/mosaicml/llm-foundry/blob/6dcc18a5d1db104b48eacce68144db5a99da37d7/.github/workflows/pr-gpu.yaml#L19) only runs this GA if the repo owner is Databricks. I added this to make things consistent.

only run GA if repo owner is Databricks

---

.github/workflows/pr-gpu.yaml
megablocks/backend/kernels.py
pyproject.toml
setup.py

**Update:** Running the latest tests manually and they pass [here](https://github.com/databricks/megablocks/actions/runs/10633150010)
* use "torch >= 2.4.0, < 2.4.1" in setup.py, pyproject.toml
* use forks of grouped_gemm, stk that support torch2.4
* will update to official versions of groupped_gemm, stk once they are released
* use newer version of composer that supports torch2.4
* will use official version of composer once it is released
* tests use torch2.4 image
This Github Actions here run the old tests and predictably fail. I manually ran the new Github Actions [here](https://github.com/databricks/megablocks/actions/runs/10564911758) and they all pass.

Bump torch to <2.4.1

---

megablocks/layers/glu.py
megablocks/layers/mlp.py

Addresses the deprecation warning:
```
/usr/lib/python3/dist-packages/turbo/quantized_linear.py:16: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
@custom_fwd
```

Remove deprecated torch.cuda.amp custom fwd and bwd 

---

megablocks/layers/arguments.py
megablocks/layers/router.py
tests/layers/dmoe_test.py
tests/layers/moe_test.py

Z-loss is an additional term that improves the stability of softmax logit inputs by penalizing large values where the float precision is reduced.
Idea was introduced by the ST-MoE Paper - https://arxiv.org/abs/2202.08906. And has been recently used in the OLMoE work - https://arxiv.org/abs/2409.02060.
Alternative implementation of https://github.com/databricks/megablocks/pull/133 
- Unsure where to document things
- Added a `test_moe_forward_backward_with_zloss` and `test_moe_forward_backward_with_zloss`

Implement Router Z-loss

---

megablocks/layers/arguments.py

This way, we can import the library without requiring a GPU to be present.
Do not query the `torch.cuda.current_device()` upon importing the library. Instead, query it when we actually instantiate the arguments struct.
Not submitted.

Initialize default device lazily

---

.github/workflows/pr-gpu.yaml
.pre-commit-config.yaml
megablocks/layers/arguments.py
pyproject.toml
setup.py
tests/layers/dmoe_test.py
tests/layers/glu_test.py
tests/layers/moe_test.py

Updated PyTorch like in https://github.com/databricks/megablocks/pull/167, but also disabling `sparse` support (only supporting `grouped` support) until we fix the issue with `triton`. Also updated `pycln` version that's breaking pre-commit checks.
For full context:
`triton 3.2.0` introduced some change to how it handles dtype promotion when two binary operands have different dtypes, and as a result we're encountering an int16 overflow in the `stk` dependency of megablocks which results in an illegal memory access (IMA). A fix like https://github.com/stanford-futuredata/stk/pull/17/files needs to be applied to to stk instead of megablocks or triton to resolve this initial issue. Even if we don't hit an IMA, not having this casting will lead to different outputs in `triton 3.1` and `triton …

Updated pytorch and disabled sparse tests

---

.github/workflows/code-quality.yaml
.github/workflows/pr-gpu.yaml
pyproject.toml

wheel released a new version, that no longer has bdist_wheel in it (https://github.com/pypa/wheel/releases/tag/0.46.0), relying on the fact that is now in setuptools, but we pin an old setuptools, and so install fails.
This PR updates setuptools to use the latest version, 78.1.0.

Update setuptools version

---

setup.py

As title, includes a tighter torch pin for grouped-gemm to prevent installation issues.

Update grouped-gemm to 0.2.0

---

megablocks/layers/arguments.py

Sets the default value of `mlp_impl` to `grouped` in `megablocks/layers/arguments/Arguments` dataclass.
This is done to avoid the default dmoe script in `exp/dmoe/dmoe_46m_8gpu.sh` to crash with:
```
[rank0]:   File "/home/mark/codes/megablocks/megablocks/layers/arguments.py", line 82, in __post_init__
[rank0]:     raise ValueError(
[rank0]: ValueError: Sparse MLP is not supported with triton >=3.2.0. Please use mlp_impl="grouped" instead.
```
Fixes #170

set default value of mlp_impl to grouped in layers/arguments
